/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  SimpleTest,
  SimpleTestInterface,
} from "../../contracts/SimpleTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "hasSurvey",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "setSurvey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "test",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460135760e1908160188239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c9081633466c9b214608e5750806388f067e71460665763f8a8fd6d146039575f80fd5b346062575f366003190112606257335f525f602052602060ff60405f2054166040519015158152f35b5f80fd5b346062575f366003190112606257335f525f60205260405f20600160ff198254161790555f80f35b3460625760203660031901126062576004359073ffffffffffffffffffffffffffffffffffffffff82168092036062576020915f525f825260ff60405f20541615158152f3fea164736f6c634300081b000a";

type SimpleTestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SimpleTestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SimpleTest__factory extends ContractFactory {
  constructor(...args: SimpleTestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SimpleTest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SimpleTest__factory {
    return super.connect(runner) as SimpleTest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SimpleTestInterface {
    return new Interface(_abi) as SimpleTestInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SimpleTest {
    return new Contract(address, _abi, runner) as unknown as SimpleTest;
  }
}
