/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MentalHealthSurvey } from "./MentalHealthSurvey";
export type { SimpleTest } from "./SimpleTest";
export type { TestFHE } from "./TestFHE";
