/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MentalHealthSurveyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getAllResponses"
      | "getAnxiety"
      | "getMood"
      | "getParticipantAtIndex"
      | "getSleepQuality"
      | "getSocialConnection"
      | "getStressIndex"
      | "getStressLevel"
      | "getTimestamp"
      | "getTotalParticipants"
      | "hasSurveyResponse"
      | "submitSurvey"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "StressIndexCalculated" | "SurveySubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllResponses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAnxiety",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getMood", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getParticipantAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSleepQuality",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSocialConnection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStressIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStressLevel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalParticipants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSurveyResponse",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitSurvey",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllResponses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAnxiety", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMood", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSleepQuality",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSocialConnection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStressIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStressLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSurveyResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSurvey",
    data: BytesLike
  ): Result;
}

export namespace StressIndexCalculatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveySubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MentalHealthSurvey extends BaseContract {
  connect(runner?: ContractRunner | null): MentalHealthSurvey;
  waitForDeployment(): Promise<this>;

  interface: MentalHealthSurveyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAllResponses: TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string, bigint] & {
        q1: string;
        q2: string;
        q3: string;
        q4: string;
        q5: string;
        index: string;
        time: bigint;
      }
    ],
    "view"
  >;

  getAnxiety: TypedContractMethod<[], [string], "view">;

  getMood: TypedContractMethod<[], [string], "view">;

  getParticipantAtIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getSleepQuality: TypedContractMethod<[], [string], "view">;

  getSocialConnection: TypedContractMethod<[], [string], "view">;

  getStressIndex: TypedContractMethod<[], [string], "view">;

  getStressLevel: TypedContractMethod<[], [string], "view">;

  getTimestamp: TypedContractMethod<[], [bigint], "view">;

  getTotalParticipants: TypedContractMethod<[], [bigint], "view">;

  hasSurveyResponse: TypedContractMethod<[], [boolean], "view">;

  submitSurvey: TypedContractMethod<
    [
      _q1: BytesLike,
      _q1Proof: BytesLike,
      _q2: BytesLike,
      _q2Proof: BytesLike,
      _q3: BytesLike,
      _q3Proof: BytesLike,
      _q4: BytesLike,
      _q4Proof: BytesLike,
      _q5: BytesLike,
      _q5Proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllResponses"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string, bigint] & {
        q1: string;
        q2: string;
        q3: string;
        q4: string;
        q5: string;
        index: string;
        time: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAnxiety"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMood"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getParticipantAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getSleepQuality"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSocialConnection"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStressIndex"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStressLevel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalParticipants"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasSurveyResponse"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitSurvey"
  ): TypedContractMethod<
    [
      _q1: BytesLike,
      _q1Proof: BytesLike,
      _q2: BytesLike,
      _q2Proof: BytesLike,
      _q3: BytesLike,
      _q3Proof: BytesLike,
      _q4: BytesLike,
      _q4Proof: BytesLike,
      _q5: BytesLike,
      _q5Proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "StressIndexCalculated"
  ): TypedContractEvent<
    StressIndexCalculatedEvent.InputTuple,
    StressIndexCalculatedEvent.OutputTuple,
    StressIndexCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "SurveySubmitted"
  ): TypedContractEvent<
    SurveySubmittedEvent.InputTuple,
    SurveySubmittedEvent.OutputTuple,
    SurveySubmittedEvent.OutputObject
  >;

  filters: {
    "StressIndexCalculated(address,uint256)": TypedContractEvent<
      StressIndexCalculatedEvent.InputTuple,
      StressIndexCalculatedEvent.OutputTuple,
      StressIndexCalculatedEvent.OutputObject
    >;
    StressIndexCalculated: TypedContractEvent<
      StressIndexCalculatedEvent.InputTuple,
      StressIndexCalculatedEvent.OutputTuple,
      StressIndexCalculatedEvent.OutputObject
    >;

    "SurveySubmitted(address,uint256)": TypedContractEvent<
      SurveySubmittedEvent.InputTuple,
      SurveySubmittedEvent.OutputTuple,
      SurveySubmittedEvent.OutputObject
    >;
    SurveySubmitted: TypedContractEvent<
      SurveySubmittedEvent.InputTuple,
      SurveySubmittedEvent.OutputTuple,
      SurveySubmittedEvent.OutputObject
    >;
  };
}
